# ==========================================
# Application
# ==========================================
spring.application.name=notification-engine

# ==========================================
# PostgreSQL
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/notification_engine
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# JPA
# ==========================================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# ==========================================
# Server
# ==========================================
server.port=8080