# ==========================================
# Application
# ==========================================
spring.application.name=notification-engine

application.name=notification-engine
application.version=0.5.0-SNAPSHOT

# ==========================================
# Background Worker
# ==========================================
application.worker.batch-size=10
application.worker.poll-interval-ms=1000

# ==========================================
# PostgreSQL
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/notification_engine
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# JPA
# ==========================================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# ==========================================
# Server
# ==========================================
server.port=8080